"""add_currency_and_unit

Revision ID: 2131fcc72ccc
Revises: b2c3d4e5f6g7
Create Date: 2026-04-14 15:19:47.060295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2131fcc72ccc'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_data', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('master_data', 'validation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('master_data', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('master_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('master_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_master_data_validation_status'), 'master_data', ['validation_status'], unique=False)
    op.add_column('master_data_records', sa.Column('currency', sa.String(length=20), nullable=True))
    op.add_column('master_data_records', sa.Column('unit', sa.String(length=50), nullable=True))
    op.alter_column('master_data_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('master_data_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_mdr_company_name'), table_name='master_data_records')
    op.drop_index(op.f('ix_mdr_document_id'), table_name='master_data_records')
    op.drop_index(op.f('ix_mdr_master_data_id'), table_name='master_data_records')
    op.drop_index(op.f('ix_mdr_period'), table_name='master_data_records')
    op.create_index(op.f('ix_master_data_records_company_name'), 'master_data_records', ['company_name'], unique=False)
    op.create_index(op.f('ix_master_data_records_document_id'), 'master_data_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_master_data_records_master_data_id'), 'master_data_records', ['master_data_id'], unique=False)
    op.create_index(op.f('ix_master_data_records_period'), 'master_data_records', ['period'], unique=False)
    op.alter_column('source_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_master_data_records_period'), table_name='master_data_records')
    op.drop_index(op.f('ix_master_data_records_master_data_id'), table_name='master_data_records')
    op.drop_index(op.f('ix_master_data_records_document_id'), table_name='master_data_records')
    op.drop_index(op.f('ix_master_data_records_company_name'), table_name='master_data_records')
    op.create_index(op.f('ix_mdr_period'), 'master_data_records', ['period'], unique=False)
    op.create_index(op.f('ix_mdr_master_data_id'), 'master_data_records', ['master_data_id'], unique=False)
    op.create_index(op.f('ix_mdr_document_id'), 'master_data_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_mdr_company_name'), 'master_data_records', ['company_name'], unique=False)
    op.alter_column('master_data_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('master_data_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('master_data_records', 'unit')
    op.drop_column('master_data_records', 'currency')
    op.drop_index(op.f('ix_master_data_validation_status'), table_name='master_data')
    op.alter_column('master_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('master_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('master_data', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'v3'::character varying"),
               existing_nullable=False)
    op.alter_column('master_data', 'validation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('master_data', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
