"""add_details_to_audit_log

Revision ID: 650c1f8c1fb6
Revises: 90d0a1d815a5
Create Date: 2026-03-17 15:01:47.786472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650c1f8c1fb6'
down_revision: Union[str, Sequence[str], None] = '90d0a1d815a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###
