"""rename_password_to_hashed_password

Revision ID: 6792d9d4aa00
Revises: 069310b1cfc7
Create Date: 2026-03-17 14:57:18.251026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6792d9d4aa00'
down_revision: Union[str, Sequence[str], None] = '069310b1cfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
